# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ARslY36o8n8IOkTC-gFk2U4vWSZxE0kF
"""

import streamlit as st
import pandas as pd
import joblib

# ---------------- PAGE CONFIG ----------------
st.set_page_config(
    page_title="AI Customer Segmentation",
    page_icon="👥",
    layout="wide"
)

# ---------------- LOAD FILES ----------------
@st.cache_resource
def load_files():
    model = joblib.load("kmeans_model.pkl")
    scaler = joblib.load("scaler.pkl")
    columns = joblib.load("columns.pkl")
    return model, scaler, columns

kmeans, scaler, training_columns = load_files()

# ---------------- CUSTOM CSS ----------------
st.markdown("""
<style>
.main{
    background:#f5f7fb;
}

.title{
    font-size:38px;
    font-weight:bold;
    color:#003366;
}

.subtitle{
    font-size:18px;
    color:gray;
}

div.stButton > button{
    width:100%;
    height:55px;
    font-size:20px;
    border-radius:12px;
    background:#0066cc;
    color:white;
}

div.stButton > button:hover{
    background:#004c99;
}
</style>
""", unsafe_allow_html=True)

# ---------------- SIDEBAR ----------------

st.sidebar.image("https://img.icons8.com/color/96/customer-insight.png", width=90)

st.sidebar.title("AI Dashboard")

st.sidebar.info("""
### Customer Segmentation

Machine Learning Algorithm

✔ K-Means Clustering

Dataset

✔ 8068 Customers

Purpose

✔ Customer Group Analysis
""")

# ---------------- HEADER ----------------

st.markdown("<div class='title'>👥 AI Customer Segmentation Dashboard</div>", unsafe_allow_html=True)

st.markdown("<div class='subtitle'>Predict which customer segment a new customer belongs to using Machine Learning.</div>", unsafe_allow_html=True)

st.divider()

# ---------------- FILE UPLOAD ----------------

st.subheader("📂 Upload Customer Dataset")

uploaded_file = st.file_uploader(
    "Upload CSV or Excel File",
    type=["csv", "xlsx"]
)

if uploaded_file is not None:

    if uploaded_file.name.endswith(".csv"):
        df = pd.read_csv(uploaded_file)
    else:
        df = pd.read_excel(uploaded_file)

    st.success(f"Dataset Loaded Successfully ({len(df)} Customers)")

    st.subheader("Preview Dataset")

    st.dataframe(df.head())

    predict = st.button("🚀 Run Customer Segmentation")
if uploaded_file is not None and predict:

    input_df = df.copy()

    # Remove ID column
if "ID" in input_df.columns:
    input_df = input_df.drop("ID", axis=1)

# Fill missing values
input_df = input_df.fillna(0)

# One-Hot Encoding
input_df = pd.get_dummies(input_df)

# Match Training Columns
input_df = input_df.reindex(
    columns=training_columns,
    fill_value=0
)

# Convert bool to int
bool_cols = input_df.select_dtypes(include=["bool"]).columns
input_df[bool_cols] = input_df[bool_cols].astype(int)

# Convert everything to numeric
input_df = input_df.astype(float)

# Scale data
scaled_data = scaler.transform(input_df)

    # Predict All Customers
    clusters = kmeans.predict(scaled_data)

    df["Cluster"] = clusters

    cluster_names = {
        0: "Stable Customer",
        1: "Premium Customer",
        2: "Young Customer"
    }

    df["Segment"] = df["Cluster"].map(cluster_names)

    st.success("Segmentation Completed Successfully")

    st.subheader("📊 Segmented Customers")

    st.dataframe(df)

    st.subheader("📈 Segment Distribution")

    cluster_counts = df["Segment"].value_counts()

    st.bar_chart(cluster_counts)

    st.subheader("📋 Segment Summary")

    col1, col2, col3 = st.columns(3)

    with col1:
        st.metric(
            "Stable Customers",
            int((df["Cluster"] == 0).sum())
        )

    with col2:
        st.metric(
            "Premium Customers",
            int((df["Cluster"] == 1).sum())
        )

    with col3:
        st.metric(
            "Young Customers",
            int((df["Cluster"] == 2).sum())
        )

    csv = df.to_csv(index=False)

    st.download_button(
        label="📥 Download Segmented Dataset",
        data=csv,
        file_name="segmented_customers.csv",
        mime="text/csv"
    )
