# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tghT6mDLCpyd_omiQEXiu29Sxkhi0mNw
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib


# -----------------------------
# Page Configuration
# -----------------------------
st.set_page_config(
    page_title="Customer Segmentation AI",
    page_icon="👥",
    layout="wide"
)


# -----------------------------
# Load Model and Scaler
# -----------------------------
@st.cache_resource
def load_model():
    model = joblib.load("kmeans_model.pkl")
    scaler = joblib.load("scaler.pkl")
    return model, scaler


kmeans, scaler = load_model()


# -----------------------------
# Title Section
# -----------------------------
st.title("👥 Customer Segmentation AI")
st.write(
    "Use Machine Learning to identify customer groups "
    "and understand customer behaviour."
)

st.divider()


# -----------------------------
# Customer Input
# -----------------------------

st.subheader("Enter Customer Information")


col1, col2, col3 = st.columns(3)


with col1:

    age = st.number_input(
        "Age",
        min_value=18,
        max_value=100,
        value=30
    )

    work_experience = st.number_input(
        "Work Experience",
        min_value=0,
        max_value=50,
        value=3
    )


with col2:

    family_size = st.number_input(
        "Family Size",
        min_value=1,
        max_value=10,
        value=3
    )


    gender = st.selectbox(
        "Gender",
        ["Male", "Female"]
    )


with col3:

    married = st.selectbox(
        "Ever Married",
        ["Yes", "No"]
    )


    graduated = st.selectbox(
        "Graduated",
        ["Yes", "No"]
    )


# Other Information

st.subheader("Lifestyle Information")


col4, col5, col6 = st.columns(3)


with col4:

    profession = st.selectbox(
        "Profession",
        [
            "Artist",
            "Doctor",
            "Engineer",
            "Entertainment",
            "Executive",
            "Healthcare",
            "Homemaker",
            "Lawyer",
            "Marketing"
        ]
    )


with col5:

    spending_score = st.selectbox(
        "Spending Score",
        [
            "Low",
            "Average",
            "High"
        ]
    )


with col6:

    var_1 = st.selectbox(
        "Category",
        [
            "Cat_1",
            "Cat_2",
            "Cat_3",
            "Cat_4",
            "Cat_5",
            "Cat_6",
            "Cat_7"
        ]
    )


st.divider()


# -----------------------------
# Prediction
# -----------------------------

if st.button("🔍 Predict Customer Segment"):


    # Create input dataframe

    input_data = pd.DataFrame({

        "Age":[age],

        "Work_Experience":[work_experience],

        "Family_Size":[family_size],

        "Gender":[gender],

        "Ever_Married":[married],

        "Graduated":[graduated],

        "Profession":[profession],

        "Spending_Score":[spending_score],

        "Var_1":[var_1]

    })


    # Same preprocessing used during training

    input_encoded = pd.get_dummies(
        input_data
    )


    # Match training columns

    training_columns = scaler.feature_names_in_


    input_encoded = input_encoded.reindex(
        columns=training_columns,
        fill_value=0
    )


    # Scaling

    input_scaled = scaler.transform(
        input_encoded
    )


    # Prediction

    prediction = kmeans.predict(
        input_scaled
    )[0]


    # -----------------------------
    # Result Display
    # -----------------------------


    st.success(
        f"Customer belongs to Cluster {prediction}"
    )


    st.subheader("Customer Segment Description")


    if prediction == 0:

        st.info(
            """
            ### Cluster 0: Stable Customers

            👤 Middle-aged customers
            💍 Mostly married
            🎓 Mostly graduates
            💰 Lower spending behaviour

            Business Strategy:
            - Provide personalised offers
            - Encourage higher spending
            """
        )


    elif prediction == 1:

        st.success(
            """
            ### Cluster 1: Premium Customers

            👤 Older customers
            💍 Married customers
            💎 High spending behaviour

            Business Strategy:
            - Loyalty programs
            - Premium products
            - Exclusive rewards
            """
        )


    else:

        st.warning(
            """
            ### Cluster 2: Young Customers

            👤 Younger customers
            🏠 Larger families
            💰 Lower spending behaviour

            Business Strategy:
            - Discounts
            - Budget products
            - Engagement campaigns
            """
        )


# -----------------------------
# Footer
# -----------------------------

st.divider()

st.caption(
    "Built using Machine Learning | K-Means Clustering"
)