# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ARslY36o8n8IOkTC-gFk2U4vWSZxE0kF
"""

import streamlit as st
import pandas as pd
import joblib

# ---------------- PAGE CONFIG ----------------

st.set_page_config(
    page_title="AI Customer Segmentation",
    page_icon="👥",
    layout="wide"
)

# ---------------- LOAD MODEL FILES ----------------

@st.cache_resource
def load_files():
    kmeans = joblib.load("kmeans_model.pkl")
    scaler = joblib.load("scaler.pkl")
    training_columns = joblib.load("columns.pkl")
    return kmeans, scaler, training_columns

kmeans, scaler, training_columns = load_files()

# ---------------- CUSTOM CSS ----------------

st.markdown("""
<style>

.title{
    font-size:38px;
    font-weight:bold;
    color:#003366;
}

.subtitle{
    font-size:18px;
    color:gray;
}

div.stButton > button{
    width:100%;
    height:55px;
    border-radius:12px;
    background:#0066cc;
    color:white;
    font-size:18px;
}

</style>
""", unsafe_allow_html=True)

# ---------------- SIDEBAR ----------------

st.sidebar.title("AI Dashboard")

st.sidebar.info("""
### Customer Segmentation

✔ K-Means Clustering

✔ 8068 Customers

✔ Business Analytics
""")

# ---------------- HEADER ----------------

st.markdown(
    "<div class='title'>👥 AI Customer Segmentation Dashboard</div>",
    unsafe_allow_html=True
)

st.markdown(
    "<div class='subtitle'>Upload a customer dataset and automatically segment customers.</div>",
    unsafe_allow_html=True
)

st.divider()
# ---------------- FILE UPLOAD ----------------

st.subheader("📂 Upload Customer Dataset")

uploaded_file = st.file_uploader(
    "Upload CSV or Excel File",
    type=["csv", "xlsx"]
)

if uploaded_file is not None:

    # Read file

    if uploaded_file.name.endswith(".csv"):
        df = pd.read_csv(uploaded_file)
    else:
        df = pd.read_excel(uploaded_file)

    st.success(
        f"Dataset Loaded Successfully ({len(df)} Customers)"
    )

    st.subheader("Preview Dataset")

    st.dataframe(df.head())

    predict = st.button("🚀 Run Customer Segmentation")

    if predict:

        input_df = df.copy()

        # Remove ID

        if "ID" in input_df.columns:
            input_df.drop("ID", axis=1, inplace=True)

        # Fill Missing Values

        input_df = input_df.fillna(0)

        # SAME ENCODING AS TRAINING

        input_df = pd.get_dummies(
            input_df,
            columns=[
                "Gender",
                "Ever_Married",
                "Graduated",
                "Profession",
                "Spending_Score",
                "Var_1"
            ],
            drop_first=True
        )

        # Match Training Columns

        input_df = input_df.reindex(
            columns=scaler.feature_names_in_,
            fill_value=0
        )
        input_df = input_df.astype(float)

        # Convert Bool → Int

        bool_cols = input_df.select_dtypes(
            include=["bool"]
        ).columns

        input_df[bool_cols] = (
            input_df[bool_cols].astype(int)
        )

        # Convert Everything to Float

        input_df = input_df.astype(float)

        
        st.write(list(input_df.columns))
        st.write("Scaler Shape:", len(scaler.feature_names_in_))
        st.write("Input Shape:", len(input_df.columns))
        st.write(input_df.dtypes)
        input_df = input_df.apply(pd.to_numeric, errors="coerce")
        input_df = input_df.fillna(0)
        # ---------------- SCALE ----------------
        
        scaled_data = scaler.transform(input_df)

        # ---------------- PREDICT ----------------

        clusters = kmeans.predict(scaled_data)

        df["Cluster"] = clusters

        cluster_names = {
            0: "Stable Customer",
            1: "Premium Customer",
            2: "Young Customer"
        }

        df["Segment"] = df["Cluster"].map(
            cluster_names
        )

        st.success(
            "✅ Customer Segmentation Completed"
        )

        # ---------------- TABLE ----------------

        st.subheader("📊 Segmented Customers")

        st.dataframe(df)

        # ---------------- CHART ----------------

        st.subheader("📈 Segment Distribution")

        cluster_counts = (
            df["Segment"]
            .value_counts()
        )

        st.bar_chart(cluster_counts)

        # ---------------- METRICS ----------------

        st.subheader("📋 Segment Summary")

        col1, col2, col3 = st.columns(3)

        with col1:
            st.metric(
                "Stable Customers",
                int((df["Cluster"] == 0).sum())
            )

        with col2:
            st.metric(
                "Premium Customers",
                int((df["Cluster"] == 1).sum())
            )

        with col3:
            st.metric(
                "Young Customers",
                int((df["Cluster"] == 2).sum())
            )

        # ---------------- DOWNLOAD ----------------

        csv = df.to_csv(index=False)

        st.download_button(
            label="📥 Download Segmented Dataset",
            data=csv,
            file_name="segmented_customers.csv",
            mime="text/csv"
        )
